config/routes.rb
Rails.application.routes.draw do
  resources :patients, param: :patient_id

  resources :patients, only: [] do
    resources :backgrounds, param: :background_id
    resources :laboratories, param: :laboratory_id
    resources :pregnancies, param: :pregnancy_id
  end

  resources :patients, only: [] do
    resources :pregnancies, only: [] do
      resources :controls, param: :control_id
      resources :images, param: :image_id
    end
  end

  get 'search' => 'patients#search'

  root 'patients#index'
end

app/models/pregnancy.rb
class Pregnancy < ActiveRecord::Base
  belongs_to :patient
  has_many   :controls, :dependent => :destroy
  has_many   :images, :dependent => :destroy

  validates  :patient_id, presence: true

  validates  :status, uniqueness: true, if: :pregnancy_is_true?

  def pregnancy_is_true?
    status == true
  end
end

app/controllers/pregnancies_controller.rb
class PregnanciesController < ApplicationController
  before_action :current_pregnancy, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @pregnancies = Pregnancy.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 7)

    respond_with @pregnancies
  end

  def show
    respond_with @pregnancy
  end

  def new
    @pregnancy = current_patient.pregnancies.new

    respond_with @pregnancy
  end

  def edit
    respond_with @pregnancy
  end

  def create
    @pregnancy = current_patient.pregnancies.new pregnancy_params

    if @pregnancy.save
      flash[:notice] = 'Embarazo agregado de forma exitosa.'
      respond_with @pregnancy, location: patient_pregnancies_path(:patient_id =>current_patient)
    else
      flash[:error] = 'Ha ocurrido un problema.'
      render :new
    end
  end

  def update
    if @pregnancy.update pregnancy_params
      flash[:notice] = 'Embarazo actualizado de forma exitosa.'
      respond_with @pregnancy, location: patient_pregnancies_path(:patient_id =>current_patient)
    else
      flash[:error] = 'Ha ocurrido un problema.'
      render :edit
    end
  end

  def destroy
    @pregnancy.destroy
    redirect_to patient_pregnancies_url, notice: 'Embarazo eliminado de forma exitosa.'
  end

  private
    def pregnancy_params
      params.require(:pregnancy).permit(:patient_id, :status, :fur, :fpp)
    end
end

app/helpers/pregnancies_helper.rb
module PregnanciesHelper
end

app/views/pregnancies/_form.html.erb
<%= simple_form_for([@patient,@pregnancy]) do |f| %>
  <%= f.error_notification %>

  <div class="col-md-12 space">
    <div class="col-md-3 col-md-push-1">
      <%= f.input :status,
            :as => :select,
            :collection => [['Activo',true], ['Pasado',false]],
            :include_blank => false,
            :label => "Status" %>
    </div>
    <div class="col-md-3 col-md-push-2">
      <label>Fecha Ultima Regla</label>
      <input class="custom-datepicker form-control center_input_text" type="text" placeholder="DD/MM/YYYY" readonly='true' name="pregnancy[fur]" id="pregnancy_fur" value=<%= if @pregnancy.fur.present?; @pregnancy.fur.strftime("%d-%m-%Y"); end %>>
    </div>
    <div class="col-md-3 col-md-push-3">
      <label>Fecha Probable Parto</label>
      <input class="custom-datepicker form-control center_input_text" type="text" placeholder="DD/MM/YYYY" readonly='true' name="pregnancy[fpp]" id="pregnancy_fpp" value=<%= if @pregnancy.fpp.present?; @pregnancy.fpp.strftime("%d-%m-%Y"); end %>>
    </div>
  </div>

  <div class="col-md-12 space"></div>

  <div class="col-md-4 col-md-push-2 center-div">
    <%= f.button :submit, ( f.object.new_record? ? "Crear" : "Actualizar"), {class: 'btn btn-primary btn-block'} %>
  </div>
<% end %>

app/views/pregnancies/edit.html.erb
<div class="wrapper">
  <div class="col-md-12 space">
    <h1 class="first_title">
      Editar Embarazo
    </h1>
  </div>

  <%= render 'form' %>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%= link_to 'Volver', patient_pregnancies_path, {class: 'btn btn-primary btn-block'} %>
  </div>

  <div class="col-md-12 space"></div>
</div>

app/views/pregnancies/index.html.erb
<div class="wrapper">
  <div class="col-md-12">
    <h1 class="first_title">Listado de Embarazos</h1>
  </div>

  <div class="col-md-12">
    <div class="col-md-12 col-md-push-1">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Estado</th>
            <th>FUR</th>
            <th>FPP</th>
            <th>Control</th>
            <th>Imagenes</th>
            <th>Eliminar</th>
          </tr>
        </thead>
        <tbody >
          <% @pregnancies.each do |pregnancy| %>
            <tr data-link="<%= edit_patient_pregnancy_path(:patient_id => current_patient, :pregnancy_id => pregnancy) %>" class="data-row">
              <td class="col-md-1"> <%= pregnancy.status == true ? 'Activo' : 'Pasado' %> </td>
              <td class="col-md-2"> <%= pregnancy.fur.present? ? pregnancy.fur.strftime("%d-%m-%Y") : 'Sin Fecha' %> </td>
              <td class="col-md-3"> <%= pregnancy.fpp.present? ? pregnancy.fpp.strftime("%d-%m-%Y") : 'Sin Fecha' %> </td>
              <td class="col-md-2">
                <%=
                    link_to_if(pregnancy.controls.empty?, 'Control de Embarazo', new_patient_pregnancy_control_path(:pregnancy_id => pregnancy), {class: 'btn btn-success btn-sm'}) do
                      link_to 'Control de Embarazo', patient_pregnancy_controls_path(:pregnancy_id => pregnancy), {class: 'btn btn-success btn-sm'}
                    end
                %>
              </td>
              <td class="col-md-2">
                <%=
                    link_to_if(pregnancy.images.empty?, 'Imagenes', new_patient_pregnancy_image_path(:pregnancy_id => pregnancy), {class: 'btn btn-success btn-sm'}) do
                      link_to 'Imagenes', patient_pregnancy_images_path(:pregnancy_id => pregnancy), {class: 'btn btn-success btn-sm'}
                    end
                %>
              </td>
              <td class="col-md-2">
                <%= link_to 'Eliminar Embarazo', patient_pregnancy_path(patient_id: current_patient, pregnancy_id: pregnancy.id), :method => 'delete', data: { confirm: '¿Estas seguro?' }, :class => 'btn btn-danger btn-sm' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <br>

  <div class="col-md-12 center-div">
    <%= will_paginate @patients, :next_label => 'Siguiente', :previous_label => 'Anterior', renderer: BootstrapPagination::Rails %>
  </div>

  <div class="col-md-12 space"></div>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%= link_to 'Agregar Embarazo', new_patient_pregnancy_path, {class: 'btn btn-primary btn-block'} %>
  </div>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%= link_to 'Volver', patient_path, {class: 'btn btn-primary btn-block'} %>
  </div>
</div>

app/views/pregnancies/new.html.erb
<div class="wrapper">
  <div class="col-md-12 space">
    <h1 class="first_title">
      Agregar Nuevo Embarazo
    </h1>
  </div>

  <%= render 'form' %>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%=
      link_to_if(current_patient.pregnancies.empty?, 'Volver', patient_path(current_patient), {class: 'btn btn-primary btn-block'}) do
        link_to 'Volver', patient_pregnancies_path, {class: 'btn btn-primary btn-block'}
      end
    %>
  </div>

  <div class="col-md-12 space"></div>
</div>

app/views/pregnancies/show.html.erb
<div class="wrapper">
  <div class="col-md-12 space"></div>
  <div class="col-md-12">
    <h1 class="first_title">
      Informacion del Embarazo
    </h1>
  </div>

  <div class="col-md-12 space"></div>

  <div class="col-md-12 space">
    <div class="col-md-3 col-md-push-1">
      <div class="col-md-12">
        <p class="label-tag"> Estado: </p>
      </div>
      <div class="col-md-12">
        <p class="data"> <%= @pregnancy.status == true ? 'Activo' : 'Pasado' %></p>
      </div>
    </div>
    <div class="col-md-3 col-md-push-2">
      <div class="col-md-12">
        <p class="label-tag"> Fecha: </p>
      </div>
      <div class="col-md-12">
        <input class="custom-datepicker form-control center_input_text" type="text" placeholder="DD/MM/YYYY" readonly='true' id="fur" disabled='disabled' value=<%= if @pregnancy.fur.present?; @pregnancy.fur.strftime("%d-%m-%Y"); end %>>
      </div>
    </div>
    <div class="col-md-3 col-md-push-3">
      <div class="col-md-12">
        <p class="label-tag"> Fecha: </p>
      </div>
      <div class="col-md-12">
        <input class="custom-datepicker form-control center_input_text" type="text" placeholder="DD/MM/YYYY" readonly='true' id="fpp" disabled='disabled' value=<%= if @pregnancy.fpp.present?; @pregnancy.fpp.strftime("%d-%m-%Y"); end %>>
      </div>
    </div>
  </div>

  <div class="col-md-12 space"></div>
  <div class="col-md-12 space"></div>
  <div class="col-md-12 space"></div>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%= link_to 'Editar', edit_patient_pregnancy_path(:patient_id => current_patient, :pregnancy_id => @pregnancy.id), {class: 'btn btn-primary btn-block'} %>
  </div>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%= link_to 'Volver', patient_pregnancies_path, {class: 'btn btn-primary btn-block'} %>
  </div>

  <div class="col-md-8 col-md-push-2 space">
    <%= link_to 'Volver', patient_pregnancies_path, {class: 'btn btn-primary btn-block'} %>
  </div>
</div>