config/routes.rb
Rails.application.routes.draw do
  resources :patients, param: :patient_id

  resources :patients, only: [] do
    resources :backgrounds, param: :background_id
    resources :laboratories, param: :laboratory_id
    resources :pregnancies, param: :pregnancy_id
  end

  resources :patients, only: [] do
    resources :pregnancies, only: [] do
      resources :controls, param: :control_id
      resources :images, param: :image_id
    end
  end

  get 'search' => 'patients#search'

  root 'patients#index'
end

app/models/laboratory.rb
class Laboratory < ActiveRecord::Base
  belongs_to :patient

  validates :patient_id, presence: true
end

app/controllers/laboratories_controller.rb
class LaboratoriesController < ApplicationController
  before_action :current_laboratory, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @laboratories = Laboratory.all.order("fecha DESC").paginate(:page => params[:page], :per_page => 12)

    respond_with @laboratories
  end

  def show
    respond_with @laboratory
  end

  def new
    @laboratory = current_patient.laboratories.new

    respond_with @laboratory
  end

  def edit
    respond_with @laboratory
  end

  def create
    @laboratory = current_patient.laboratories.new laboratory_params

    if @laboratory.save
      flash[:notice] = 'Laboratorio agregado de forma exitosa.'
      respond_with @laboratory, location: patient_laboratories_path
    else
      flash[:error] = 'Ha ocurrido un problema.'
      render :new
    end
  end

  def update
    if @laboratory.update laboratory_params
      flash[:notice] = 'Laboratorio actualizado de forma exitosa.'
      respond_with @laboratory, location: patient_laboratories_path
    else
      flash[:error] = 'Ha ocurrido un problema.'
      render :edit
    end
  end

  def destroy
    @laboratory.destroy
    redirect_to patient_laboratories_url, notice: 'Laboratorio eliminado de forma exitosa.'
  end

  private
    def laboratory_params
      params.require(:laboratory).permit(:patient_id, :fecha, :hb, :htc, :vdrl, :glicemia, :orina, :heces)
    end
end

app/helpers/laboratories_helper.rb
module LaboratoriesHelper
end

app/views/laboratories/_form.html.erb
<%= simple_form_for([@patient,@laboratory]) do |f| %>
  <%= f.error_notification %>

  <div class="col-md-12 space">
    <h1 class="first_title">
      Examen de Laboratorio
    </h1>
  </div>

  <div class="col-md-12 space">
    <div class="col-md-3 col-md-push-1">
      <label>Fecha</label>
      <input class="custom-datepicker form-control center_input_text" type="text" placeholder="DD/MM/YYYY" readonly='true' name="laboratory[fecha]" id="laboratory_fecha" value=<%= if @laboratory.fecha.present?; @laboratory.fecha.strftime("%d-%m-%Y"); end %>>
    </div>
    <div class="col-md-3 col-md-push-2">
      <%= f.input :hb %>
    </div>
    <div class="col-md-3 col-md-push-3">
      <%= f.input :htc %>
    </div>
  </div>

  <div class="col-md-12 space">
    <div class="col-md-3 col-md-push-1">
      <%= f.input :vdrl %>
    </div>
    <div class="col-md-3 col-md-push-2">
      <%= f.input :glicemia %>
    </div>
    <div class="col-md-3 col-md-push-3">
      <%= f.input :orina %>
    </div>
  </div>

  <div class="col-md-12 space">
    <div class="col-md-3 col-md-push-1">
      <%= f.input :heces %>
    </div>
  </div>

  <div class="col-md-12 space"></div>

  <div class="col-md-4 col-md-push-2 center-div">
    <%= f.button :submit, ( f.object.new_record? ? "Crear" : "Actualizar"), {class: 'btn btn-primary btn-block'} %>
  </div>
<% end %>

app/views/laboratories/edit.html.erb
<div class="wrapper">

  <%= render 'form' %>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%= link_to 'Volver', patient_laboratories_path, {class: 'btn btn-primary btn-block'} %>
  </div>

  <div class="col-md-12 space"></div>
</div>

app/views/laboratories/index.html.erb
<div class="wrapper">
  <div class="col-md-12">
    <h1 class="first_title">Listado de Laboratorios</h1>
  </div>

  <div class="col-md-12">
    <div class="col-md-12 col-md-push-1">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Fecha</th>
            <th>HB</th>
            <th>HTC</th>
            <th>VDRL</th>
            <th>Glicemia</th>
            <th>Orina</th>
            <th>Heces</th>
          </tr>
        </thead>
        <tbody >
          <% @laboratories.each do |laboratory| %>
            <tr data-link="<%= edit_patient_laboratory_path(:patient_id => current_patient, :laboratory_id => laboratory) %>" class="data-row">
              <td class="col-md-2"> <%= laboratory.fecha.present? ? laboratory.fecha.strftime("%d-%m-%Y") : 'Sin Fecha' %> </td>
              <td class="col-md-1"> <%= laboratory.hb %> </td>
              <td class="col-md-1"> <%= laboratory.htc %> </td>
              <td class="col-md-1"> <%= laboratory.vdrl %> </td>
              <td class="col-md-1"> <%= laboratory.glicemia %> </td>
              <td class="col-md-1"> <%= laboratory.orina %> </td>
              <td class="col-md-1"> <%= laboratory.heces %> </td>
              <td class="col-md-2">
                <%= link_to 'Eliminar Laboratorio', patient_laboratory_path(patient_id: current_patient, laboratory_id: laboratory.id), :method => 'delete', data: { confirm: '¿Estas seguro?' }, :class => 'btn btn-danger btn-sm' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>


  <br>

  <div class="col-md-12 center-div">
    <%= will_paginate @patients, :next_label => 'Siguiente', :previous_label => 'Anterior', renderer: BootstrapPagination::Rails %>
  </div>

  <div class="col-md-12 space"></div>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%= link_to 'Agregar Laboratorio', new_patient_laboratory_path(:patient_id => current_patient), {class: 'btn btn-primary btn-block'} %>
  </div>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%= link_to 'Volver', patient_path, {class: 'btn btn-primary btn-block'} %>
  </div>
</div>

app/views/laboratories/new.html.erb
<div class="wrapper">

  <%= render 'form' %>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%=
      link_to_if(current_patient.laboratories.empty?, 'Volver', patient_path(current_patient), {class: 'btn btn-primary btn-block'}) do
        link_to 'Volver', patient_laboratories_path, {class: 'btn btn-primary btn-block'}
      end
    %>
  </div>

  <div class="col-md-12 space"></div>
</div>

app/views/laboratories/show.html.erb
<div class="wrapper">
  <div class="col-md-12 space"></div>
  <div class="col-md-12">
    <h1 class="first_title">
      Informacion de - <b><%= @patient.nombre %> <%= @patient.apellido %></b>
    </h1>
  </div>

  <div class="col-md-12 space"></div>

  <div class="col-md-12 space">
    <div class="col-md-3 col-md-push-1">
      <div class="col-md-12">
        <p class="label-tag"> Fecha: </p>
      </div>
      <div class="col-md-12">
        <input class="custom-datepicker form-control center_input_text" type="text" placeholder="DD/MM/YYYY" readonly='true' id="fecha" disabled='disabled' value=<%= if @laboratory.fecha.present?; @laboratory.fecha.strftime("%d-%m-%Y"); end %>>
      </div>
    </div>
    <div class="col-md-3 col-md-push-2">
      <div class="col-md-12">
        <p class="label-tag"> HB: </p>
      </div>
      <div class="col-md-12">
        <p class="data"> <%= @laboratory.hb %> </p>
      </div>
    </div>
    <div class="col-md-3 col-md-push-3">
      <div class="col-md-12">
        <p class="label-tag"> HTC: </p>
      </div>
      <div class="col-md-12">
        <p class="data"> <%= @laboratory.htc %> </p>
      </div>
    </div>
  </div>

  <div class="col-md-12 space">
    <div class="col-md-3 col-md-push-1">
      <div class="col-md-12">
        <p class="label-tag"> VDRL: </p>
      </div>
      <div class="col-md-12">
        <p class="data"> <%= @laboratory.vdrl %> </p>
      </div>
    </div>
    <div class="col-md-3 col-md-push-2">
      <div class="col-md-12">
        <p class="label-tag"> Glicemia: </p>
      </div>
      <div class="col-md-12">
        <p class="data"> <%= @laboratory.glicemia %> </p>
      </div>
    </div>
    <div class="col-md-3 col-md-push-3">
      <div class="col-md-12">
        <p class="label-tag"> Orina: </p>
      </div>
      <div class="col-md-12">
        <p class="data"> <%= @laboratory.orina %> </p>
      </div>
    </div>
  </div>

  <div class="col-md-12 space">
    <div class="col-md-3 col-md-push-1">
      <div class="col-md-12">
        <p class="label-tag"> Heces: </p>
      </div>
      <div class="col-md-12">
        <p class="data"> <%= @laboratory.heces %> </p>
      </div>
    </div>
  </div>

  <div class="col-md-12 space"></div>
  <div class="col-md-12 space"></div>
  <div class="col-md-12 space"></div>
  <div class="col-md-12 space"></div>
  <div class="col-md-12 space"></div>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%= link_to 'Editar', edit_patient_laboratory_path(:patient_id => current_patient, :laboratory_id => @laboratory.id), {class: 'btn btn-primary btn-block'} %>
  </div>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%= link_to 'Volver', patient_laboratories_path, {class: 'btn btn-primary btn-block'} %>
  </div>

  <div class="col-md-8 col-md-push-2 space">
    <%= link_to 'Eliminar Laboratorio', patient_laboratory_path(patient_id: @patient.id, laboratory_id: @laboratory.id), :method => 'delete', data: { confirm: '¿Estas seguro?' }, :class => 'btn btn-danger btn-block' %>
  </div>
</div>