config/routes.rb
Rails.application.routes.draw do
  resources :patients, param: :patient_id

  resources :patients, only: [] do
    resources :backgrounds, param: :background_id
    resources :laboratories, param: :laboratory_id
    resources :pregnancies, param: :pregnancy_id
  end

  resources :patients, only: [] do
    resources :pregnancies, only: [] do
      resources :controls, param: :control_id
      resources :images, param: :image_id
    end
  end

  get 'search' => 'patients#search'

  root 'patients#index'
end

app/models/control.rb
class Control < ActiveRecord::Base
  belongs_to :pregnancy

  validates  :pregnancy_id, presence: true
end

app/controllers/controls_controller.rb
class ControlsController < ApplicationController
  before_action :current_pregnancy_control, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @controls = Control.all.order("fecha DESC").paginate(:page => params[:page], :per_page => 7)

    respond_with @controls
  end

  def show
    respond_with @control
  end

  def new
    @control = current_pregnancy.controls.new

    respond_with @control
  end

  def edit
    respond_with @control
  end

  def create
    @control = current_pregnancy.controls.new control_params

    if @control.save
      flash[:notice] = 'Control agregado de forma exitosa.'
      respond_with @control, location: patient_pregnancy_controls_path
    else
      flash[:error] = 'Ha ocurrido un problema.'
      render :new
    end
  end

  def update
    if @control.update control_params
      flash[:notice] = 'Control actualizado de forma exitosa.'
      respond_with @control, location: patient_pregnancy_controls_path(:patient_id =>current_patient,
                                                                 :pregnancy_id => current_pregnancy)
    else
      flash[:error] = 'Ha ocurrido un problema.'
      render :edit
    end
  end

  def destroy
    @control.destroy
    redirect_to patient_pregnancy_controls_url, notice: 'Control eliminado de forma exitosa.'
  end

  private
    def control_params
      params.require(:control).permit(:pregnancy_id, :fecha, :eg, :au, :ta, :peso, :present, :ff, :edemas)
    end
end

app/helpers/controls_helper.rb
module ControlsHelper
end

app/views/controls/_form.html.erb
<%= simple_form_for([@patient,@pregnancy,@control]) do |f| %>
    <%= f.error_notification %>

    <div class="col-md-12">
      <div class="col-md-3 col-md-push-1">
        <label>Fecha</label>
        <input class="custom-datepicker form-control center_input_text" type="text" placeholder="DD/MM/YYYY" readonly='true' name="control[fecha]" id="control_fecha" value=<%= if @control.fecha.present?; @control.fecha.strftime("%d-%m-%Y"); end %>>
      </div>
      <div class="col-md-3 col-md-push-2">
        <%= f.input :eg %>
      </div>
      <div class="col-md-3 col-md-push-3">
        <%= f.input :au %>
      </div>
    </div>

    <div class="col-md-12">
      <div class="col-md-3 col-md-push-1">
        <%= f.input :ta %>
      </div>
      <div class="col-md-3 col-md-push-2">
        <%= f.input :peso %>
      </div>
      <div class="col-md-3 col-md-push-3">
        <%= f.input :present %>
      </div>
    </div>

    <div class="col-md-12">
      <div class="col-md-3 col-md-push-1">
        <%= f.input :ff %>
      </div>
      <div class="col-md-3 col-md-push-2">
        <%= f.input :edemas %>
      </div>
    </div>

    <div class="col-md-12 space"></div>
    <div class="col-md-12 space"></div>

    <div class="col-md-4 col-md-push-2 center-div">
      <%= f.button :submit, ( f.object.new_record? ? "Crear" : "Actualizar"), {class: 'btn btn-primary btn-block'} %>
    </div>
<% end %>

app/views/controls/edit.html.erb
<div class="wrapper">
  <div class="col-md-12 space">
    <h1 class="first_title">
      Editar Control de Embarazo
    </h1>
  </div>

  <%= render 'form' %>

  <div class="col-md-4 col-md-push-3 center-div space">
    <%= link_to 'Volver', patient_pregnancy_controls_path, {class: 'btn btn-primary btn-block'} %>
  </div>

  <div class="col-md-12 space"></div>
</div>

app/views/controls/index.html.erb
<div class="wrapper">
  <div class="col-md-12">
    <h1 class="first_title">Controles del Embarazo</h1>
  </div>

  <div class="col-md-12">
    <div class="col-md-12 col-md-push-1">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Fecha</th>
            <th>EG</th>
            <th>AU</th>
            <th>TA</th>
            <th>Peso</th>
            <th>Present</th>
            <th>FF</th>
            <th>Edemas</th>
            <th>Eliminar</th>
          </tr>
        </thead>
        <tbody>
          <% @controls.each do |control| %>
            <tr data-link="<%= edit_patient_pregnancy_control_path(:patient_id => current_patient, :pregnancy_id => current_pregnancy, :control_id => control) %>" class="data-row">
              <td class="col-md-2"> <%= control.fecha.present? ? control.fecha.strftime("%d-%m-%Y") : 'Sin Fecha' %> </td>
              <td class="col-md-1"> <%= control.eg %> </td>
              <td class="col-md-1"> <%= control.au %> </td>
              <td class="col-md-1"> <%= control.ta %> </td>
              <td class="col-md-1"> <%= control.peso %> </td>
              <td class="col-md-1"> <%= control.present %> </td>
              <td class="col-md-1"> <%= control.ff %> </td>
              <td class="col-md-1"> <%= control.edemas %> </td>
              <td class="col-md-2">
                <%= link_to 'Eliminar Control', patient_pregnancy_control_path(patient_id: current_patient, pregnancy_id: current_pregnancy, control_id: control), :method => 'delete', data: { confirm: '¿Estas seguro?' }, :class => 'btn btn-danger btn-block' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <br>

  <div class="col-md-12 center-div">
    <%= will_paginate @patients, :next_label => 'Siguiente', :previous_label => 'Anterior', renderer: BootstrapPagination::Rails %>
  </div>

  <div class="col-md-12 space"></div>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%= link_to 'Agregar Control', new_patient_pregnancy_control_path, {class: 'btn btn-primary btn-block'} %>
  </div>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%= link_to 'Volver', patient_pregnancies_path, {class: 'btn btn-primary btn-block'} %>
  </div>
</div>

app/views/controls/new.html.erb
<div class="wrapper">
  <div class="col-md-12 space">
    <h1 class="first_title">
      Agregar Nuevo Control de Embarazo
    </h1>
  </div>

  <%= render 'form' %>

  <div class="col-md-4 col-md-push-3 center-div space">
    <%=
      link_to_if(current_pregnancy.controls.empty?, 'Volver', patient_pregnancies_path(current_patient), {class: 'btn btn-primary btn-block'}) do
        link_to 'Volver', patient_pregnancy_controls_path, {class: 'btn btn-primary btn-block'}
      end
    %>
  </div>

  <div class="col-md-12 space"></div>
</div>

app/views/controls/show.html.erb
<div class="wrapper">
  <div class="col-md-12">
    <h1 class="first_title">
      Cotrol del Embarazo- <b><%= @patient.nombre %> <%= @patient.apellido %></b>
    </h1>
  </div>

  <div class="col-md-12 space"></div>

  <div class="col-md-12 space">
    <div class="col-md-3 col-md-push-1">
      <label>Fecha</label>
      <input class="custom-datepicker form-control center_input_text" type="text" placeholder="DD/MM/YYYY" readonly='true' name="control[fecha]" id="control_fecha" disabled='disabled' value=<%= if @control.fecha.present?; @control.fecha.strftime("%d-%m-%Y"); end %>>
    </div>
    <div class="col-md-3 col-md-push-2">
      <div class="col-md-12">
        <p class="label-tag"> EG: </p>
      </div>
      <div class="col-md-12">
        <p class="data"> <%= @control.eg %> </p>
      </div>
    </div>
    <div class="col-md-3 col-md-push-3">
      <div class="col-md-12">
        <p class="label-tag"> AU: </p>
      </div>
      <div class="col-md-12">
        <p class="data"> <%= @control.au %> </p>
      </div>
    </div>
  </div>

  <div class="col-md-12 space"></div>

  <div class="col-md-12 space">
    <div class="col-md-3 col-md-push-1">
      <div class="col-md-12">
        <p class="label-tag"> TA: </p>
      </div>
      <div class="col-md-12">
        <p class="data"> <%= @control.ta %> </p>
      </div>
    </div>
    <div class="col-md-3 col-md-push-2">
      <div class="col-md-12">
        <p class="label-tag"> Peso: </p>
      </div>
      <div class="col-md-12">
        <p class="data"> <%= @control.peso %> </p>
      </div>
    </div>
    <div class="col-md-3 col-md-push-3">
      <div class="col-md-12">
        <p class="label-tag"> Present: </p>
      </div>
      <div class="col-md-12">
        <p class="data"> <%= @control.present %> </p>
      </div>
    </div>
  </div>

  <div class="col-md-12 space"></div>

  <div class="col-md-12 space">
    <div class="col-md-3 col-md-push-1">
      <div class="col-md-12">
        <p class="label-tag"> FF: </p>
      </div>
      <div class="col-md-12">
        <p class="data"> <%= @control.ff %> </p>
      </div>
    </div>
    <div class="col-md-3 col-md-push-2">
      <div class="col-md-12">
        <p class="label-tag"> Edemas: </p>
      </div>
      <div class="col-md-12">
        <p class="data"> <%= @control.edemas %> </p>
      </div>
    </div>
  </div>

  <div class="col-md-12 space"></div>
  <div class="col-md-12 space"></div>

  <div class="col-md-4 col-md-push-2 center-div space">
    <%= link_to 'Editar', edit_patient_pregnancy_control_path(:patient_id => current_patient, :pregnancy_id => @pregnancy, :control_id => @control), {class: 'btn btn-primary btn-block'} %>
  </div>

  <div class="col-md-4 col-md-push-3 center-div space">
    <%= link_to 'Volver', patient_pregnancy_controls_path(:patient_id => current_patient, :pregnancy_id => current_pregnancy), {class: 'btn btn-primary btn-block'} %>
  </div>
</div>