config/routes.rb
Rails.application.routes.draw do
  resources :patients, param: :patient_id

  resources :patients, only: [] do
    resources :backgrounds, param: :background_id
    resources :laboratories, param: :laboratory_id
    resources :pregnancies, param: :pregnancy_id
  end

  resources :patients, only: [] do
    resources :pregnancies, only: [] do
      resources :controls, param: :control_id
      resources :images, param: :image_id
    end
  end

  get 'search' => 'patients#search'

  root 'patients#index'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<div id="ajax-refresh-flash">
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, sanitize(msg), :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation" id="topnavbar">
  <div class="container-fluid">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Registrar Paciente', new_patient_path%></li>
        <li><%= link_to 'Listar Paciente', patients_path%></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <%= form_tag search_path, method: :get, :class=> 'navbar-form' do %>
          <div class="form-group">
            <%= text_field_tag :search_cedula, params[:search_cedula], placeholder: 'Cedula del cliente', class: 'form-control vi_client_id_number' %>
          </div>
          <%= button_tag(type: "submit", class: "btn btn-default btn-sm vi_search_client") do %>
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          <% end %>
        <% end %>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% unless current_patient.nil? %>
        <ul class="nav navbar-nav navbar-right">
          <p class="navbar-text"><span>Paciente Actual: </span></p>
          <li><%= link_to current_patient.nombre, patient_path, {class: 'navbar-link'}%></li>
        </ul>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_sidebar.html.erb
<div class="col-md-2 sidebar">
  <div class="sidebar-elements">
    <div class="sidebar-images-container background_change">
      <%= link_to(patient_background) do %>
        <p>Antecedentes</p>
        <%= image_tag("background.png", class: 'img-sidebar background')%>
      <% end %>
    </div>
    <div class="sidebar-images-container laboratory_change">
      <%= link_to(patient_laboratory) do %>
        <p>Laboratorios</p>
        <%= image_tag("laboratory.png", class: 'img-sidebar laboratory')%>
      <% end %>
    </div>
    <div class="sidebar-images-container pregnancy_change">
      <%= link_to(patient_pregnancy) do %>
        <p>Embarazos</p>
        <%= image_tag("pregnancy.png", class: 'img-sidebar pregnancy')%>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Centro Medico Maracay Gineco-Obstetra" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Centro Medico Maracay Gineco-Obstetra" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= render 'layouts/sidebar' unless current_patient.nil? %>
       <%= yield %>
    </main>
  </body>
</html>